In [113]:
import pandas as pd
import numpy as np
import pyarrow.parquet as pq
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm
import csv

In [31]:
import psutil
print(f"RAM dispo: {psutil.virtual_memory().available / 1024**3:.1f} Go")

RAM dispo: 11.6 Go

In [ ]:
def extraction_data_idf_indus(Fichier1, Fichier2):
    cols_etab = ['siren', 'siret', 'dateCreationEtablissement',
                 'trancheEffectifsEtablissement', 'denominationUsuelleEtablissement', 'dateDernierTraitementEtablissement',
                 'etablissementSiege', 'numeroVoieEtablissement', 'typeVoieEtablissement',
                 'libelleVoieEtablissement', 'codePostalEtablissement',
                 'libelleCommuneEtablissement', 'coordonneeLambertAbscisseEtablissement',
                 'coordonneeLambertOrdonneeEtablissement', 'etatAdministratifEtablissement',
                 'activitePrincipaleEtablissement', 'caractereEmployeurEtablissement', 'codePaysEtrangerEtablissement']

    dep = ('75', '77', '78', '91', '92', '93', '94', '95')
    prefixes_activite = ('10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25',
                          '26', '27', '28', '29', '30', '31', '32', '33', '35', '36', '37', '38', '39', '41', '42', '43',
                            '69', '70', '71', '72', '73', '74', '75')   # SECTION C, D, E, F, M

    pf = pq.ParquetFile(Fichier1)
    n_batches = (pf.metadata.num_rows + 49_999) // 50_000
    batches = []
    for batch in tqdm(pf.iter_batches(batch_size=50_000, columns=cols_etab),
                      total=n_batches, desc="Établissements"):
        df_batch = batch.to_pandas()
        df_batch = df_batch[
        df_batch['codePostalEtablissement'].str.startswith(dep, na=False)
        &
        # df_batch['activitePrincipaleEtablissement'].str.startswith(prefixes_activite, na=False)
        # &
        df_batch['etatAdministratifEtablissement'].str.startswith("A", na=False)
]
        batches.append(df_batch)
    df_etab = pd.concat(batches, ignore_index=True)

    cols_unit = ['siren', 'denominationUniteLegale', 'sexeUniteLegale', 'prenomUsuelUniteLegale',
                 'trancheEffectifsUniteLegale', 'categorieEntreprise', 'categorieJuridiqueUniteLegale']

    pf_2 = pq.ParquetFile(Fichier2)
    n_batches_2 = (pf_2.metadata.num_rows + 49_999) // 50_000
    batches = []
    for batch in tqdm(pf_2.iter_batches(batch_size=50_000, columns=cols_unit),
                      total=n_batches_2, desc="Unités légales"):
        batches.append(batch.to_pandas())
    df_unit = pd.concat(batches, ignore_index=True)

    resultat = pd.merge(df_etab, df_unit, on='siren', how='left')
    return resultat

In [33]:
df_fusion = extraction_data_idf_indus('data/stock-stocketablissement-parquet.parquet', 'data/stock-stockunitelegale-parquet.parquet')

Établissements:   0%|          | 0/882 [00:00<?, ?it/s]

Établissements: 100%|██████████| 882/882 [00:22<00:00, 38.75it/s]
Unités légales: 100%|██████████| 601/601 [00:12<00:00, 48.87it/s]

In [34]:
df_fusion.info()

<class 'pandas.DataFrame'>
RangeIndex: 2966640 entries, 0 to 2966639
Data columns (total 24 columns):
 #   Column                                  Dtype
---  ------                                  -----
 0   siren                                   str
 1   siret                                   str
 2   dateCreationEtablissement               object
 3   trancheEffectifsEtablissement           str
 4   denominationUsuelleEtablissement        str
 5   dateDernierTraitementEtablissement      datetime64[us]
 6   etablissementSiege                      bool
 7   numeroVoieEtablissement                 str
 8   typeVoieEtablissement                   str
 9   libelleVoieEtablissement                str
 10  codePostalEtablissement                 str
 11  libelleCommuneEtablissement             str
 12  coordonneeLambertAbscisseEtablissement  str
 13  coordonneeLambertOrdonneeEtablissement  str
 14  etatAdministratifEtablissement          str
 15  activitePrincipaleEtablissement         str
 16  caractereEmployeurEtablissement         str
 17  codePaysEtrangerEtablissement           str
 18  denominationUniteLegale                 str
 19  sexeUniteLegale                         str
 20  prenomUsuelUniteLegale                  str
 21  trancheEffectifsUniteLegale             str
 22  categorieEntreprise                     str
 23  categorieJuridiqueUniteLegale           int64
dtypes: bool(1), datetime64[us](1), int64(1), object(1), str(20)
memory usage: 851.4+ MB

In [35]:
df_fusion.head()

,siren,siret,dateCreationEtablissement,trancheEffectifsEtablissement,denominationUsuelleEtablissement,dateDernierTraitementEtablissement,etablissementSiege,numeroVoieEtablissement,typeVoieEtablissement,libelleVoieEtablissement,...,etatAdministratifEtablissement,activitePrincipaleEtablissement,caractereEmployeurEtablissement,codePaysEtrangerEtablissement,denominationUniteLegale,sexeUniteLegale,prenomUsuelUniteLegale,trancheEffectifsUniteLegale,categorieEntreprise,categorieJuridiqueUniteLegale
0,005520325,00552032500027,2018-12-20,NN,NaN,2025-12-06 04:31:28,True,36,AVENUE,JUNOT,...,A,70.10Z,N,NaN,ETABLISSEMENTS ADRIEN RIQUIER,NaN,NaN,12,PME,5710
1,005580501,00558050100046,1996-05-01,NN,NaN,2025-12-06 00:46:51,True,93,BOULEVARD,MALESHERBES,...,A,66.30Z,O,NaN,SGN PARIS INVESTISSEMENTS,NaN,NaN,NN,GE,5710
2,005720602,00572060200043,2007-03-19,NN,NaN,2025-12-05 20:27:36,True,14,RUE,MARC BLOCH,...,A,68.20B,N,NaN,SOC IMMOBILIERE MONOPRIX ABBEVILLE,NaN,NaN,NN,PME,5710
3,005720784,00572078400148,2011-01-01,NN,NaN,2025-12-06 04:56:10,False,1,IMPASSE,NICEPHORE NIEPCE,...,A,25.99A,O,NaN,ETABLISSEMENTS DECAYEUX,NaN,NaN,31,PME,5710
4,005720784,00572078400163,2021-12-23,11,ETABLISSEMENTS DECAYEUX,2025-12-05 22:11:10,False,13,RUE,DES INDUSTRIES,...,A,25.99A,O,NaN,ETABLISSEMENTS DECAYEUX,NaN,NaN,31,PME,5710

# Exclusion des entrepreneur individuels

In [69]:
df = df_fusion [df_fusion["categorieJuridiqueUniteLegale"] != 1000]

# Ajout variable nom entreprise

In [ ]:
df["non_entreprise"] = np.where(
    df["denominationUsuelleEtablissement"].isna(),
    df["denominationUniteLegale"],
    df["denominationUsuelleEtablissement"]
)

# Ajout code activité niveau 1

In [ ]:
df["niv1_activitePrincipaleEtablissement"] = df["activitePrincipaleEtablissement"].str[:2]

# Ajout Lib codes activités

In [140]:
# Charger le fichier de correspondance
naf = pd.read_csv('data/int_courts_naf_rev_2 - NAF rév. 2.csv', sep=',', encoding='utf-8')

# Merge sur le code
df = df.merge(naf[["Code", "Intitule"]],
              left_on="niv1_activitePrincipaleEtablissement",
              right_on="Code",
              how="left")

# Renommer / nettoyer
df = df.rename(columns={"Intitule": "niv1_act_lib"}).drop(columns="Code")

In [143]:
# Charger le fichier de correspondance
naf = pd.read_csv('data/int_courts_naf_rev_2 - NAF rév. 2.csv', sep=',', encoding='utf-8')

# Merge sur le code
df = df.merge(naf[["Code", "Intitule"]],
              left_on="activitePrincipaleEtablissement",
              right_on="Code",
              how="left")

# Renommer / nettoyer
df = df.rename(columns={"Intitule": "act_lib"}).drop(columns="Code")

# Ajout département

In [153]:
df["departement"] = df["codePostalEtablissement"].str[:2]

In [154]:
df["departement"].value_counts()

departement
75    815069
92    233651
93    182094
78    155005
94    154486
77    139449
95    131343
91    124269
Name: count, dtype: int64

# Supression colonne inutiles

In [146]:
df = df.drop(columns=["denominationUsuelleEtablissement", "denominationUniteLegale",])

In [ ]:
df.to_csv("resultat_idf.csv", index=False, encoding="utf-8")

# Analyse des valeurs manquantes

In [71]:
df.info()

<class 'pandas.DataFrame'>
Index: 1935366 entries, 0 to 2966639
Data columns (total 24 columns):
 #   Column                                  Dtype
---  ------                                  -----
 0   siren                                   str
 1   siret                                   str
 2   dateCreationEtablissement               object
 3   trancheEffectifsEtablissement           str
 4   denominationUsuelleEtablissement        str
 5   dateDernierTraitementEtablissement      datetime64[us]
 6   etablissementSiege                      bool
 7   numeroVoieEtablissement                 str
 8   typeVoieEtablissement                   str
 9   libelleVoieEtablissement                str
 10  codePostalEtablissement                 str
 11  libelleCommuneEtablissement             str
 12  coordonneeLambertAbscisseEtablissement  str
 13  coordonneeLambertOrdonneeEtablissement  str
 14  etatAdministratifEtablissement          str
 15  activitePrincipaleEtablissement         str
 16  caractereEmployeurEtablissement         str
 17  codePaysEtrangerEtablissement           str
 18  denominationUniteLegale                 str
 19  sexeUniteLegale                         str
 20  prenomUsuelUniteLegale                  str
 21  trancheEffectifsUniteLegale             str
 22  categorieEntreprise                     str
 23  categorieJuridiqueUniteLegale           int64
dtypes: bool(1), datetime64[us](1), int64(1), object(1), str(20)
memory usage: 574.9+ MB

In [149]:
df.isna().sum(axis=0)

siren                                           0
siret                                           0
dateCreationEtablissement                       0
trancheEffectifsEtablissement                   0
dateDernierTraitementEtablissement              0
etablissementSiege                              0
numeroVoieEtablissement                     59238
typeVoieEtablissement                       31420
libelleVoieEtablissement                     1587
codePostalEtablissement                         0
libelleCommuneEtablissement                   472
coordonneeLambertAbscisseEtablissement      83726
coordonneeLambertOrdonneeEtablissement      83726
etatAdministratifEtablissement                  0
activitePrincipaleEtablissement                 0
caractereEmployeurEtablissement              9860
codePaysEtrangerEtablissement             1934894
sexeUniteLegale                           1935366
prenomUsuelUniteLegale                    1935366
trancheEffectifsUniteLegale                     0
categorieEntreprise                        843168
categorieJuridiqueUniteLegale                   0
non_entreprise                                  0
niv1_activitePrincipaleEtablissement            0
niv1_act_lib                                    1
act_lib                                       103
dtype: int64

In [72]:
df.head()

,siren,siret,dateCreationEtablissement,trancheEffectifsEtablissement,denominationUsuelleEtablissement,dateDernierTraitementEtablissement,etablissementSiege,numeroVoieEtablissement,typeVoieEtablissement,libelleVoieEtablissement,...,etatAdministratifEtablissement,activitePrincipaleEtablissement,caractereEmployeurEtablissement,codePaysEtrangerEtablissement,denominationUniteLegale,sexeUniteLegale,prenomUsuelUniteLegale,trancheEffectifsUniteLegale,categorieEntreprise,categorieJuridiqueUniteLegale
0,005520325,00552032500027,2018-12-20,NN,NaN,2025-12-06 04:31:28,True,36,AVENUE,JUNOT,...,A,70.10Z,N,NaN,ETABLISSEMENTS ADRIEN RIQUIER,NaN,NaN,12,PME,5710
1,005580501,00558050100046,1996-05-01,NN,NaN,2025-12-06 00:46:51,True,93,BOULEVARD,MALESHERBES,...,A,66.30Z,O,NaN,SGN PARIS INVESTISSEMENTS,NaN,NaN,NN,GE,5710
2,005720602,00572060200043,2007-03-19,NN,NaN,2025-12-05 20:27:36,True,14,RUE,MARC BLOCH,...,A,68.20B,N,NaN,SOC IMMOBILIERE MONOPRIX ABBEVILLE,NaN,NaN,NN,PME,5710
3,005720784,00572078400148,2011-01-01,NN,NaN,2025-12-06 04:56:10,False,1,IMPASSE,NICEPHORE NIEPCE,...,A,25.99A,O,NaN,ETABLISSEMENTS DECAYEUX,NaN,NaN,31,PME,5710
4,005720784,00572078400163,2021-12-23,11,ETABLISSEMENTS DECAYEUX,2025-12-05 22:11:10,False,13,RUE,DES INDUSTRIES,...,A,25.99A,O,NaN,ETABLISSEMENTS DECAYEUX,NaN,NaN,31,PME,5710

# Analyse des variable discrètes

In [73]:
df["categorieEntreprise"].value_counts(normalize = True)

categorieEntreprise
PME    0.892896
ETI    0.060910
GE     0.046194
Name: proportion, dtype: float64

In [74]:
df["dateCreationEtablissement"].value_counts(normalize=True)

dateCreationEtablissement
1995-12-25    2.295845e-02
1900-01-01    7.095815e-03
2025-01-01    2.977731e-03
2024-01-01    2.835639e-03
2026-01-01    2.610359e-03
                  ...
1962-09-10    5.166981e-07
1982-01-24    5.166981e-07
1949-02-11    5.166981e-07
1938-05-19    5.166981e-07
1955-04-04    5.166981e-07
Name: proportion, Length: 22940, dtype: float64

In [75]:
df["activitePrincipaleEtablissement"].value_counts()

activitePrincipaleEtablissement
68.20B    357244
94.99Z    108296
70.22Z     97567
81.10Z     68789
68.20A     66488
           ...
05.10Z         1
01.64Z         1
01.15Z         1
01.12Z         1
10.51B         1
Name: count, Length: 725, dtype: int64

In [76]:
df["trancheEffectifsEtablissement"].value_counts()

trancheEffectifsEtablissement
NN    1577839
01     147915
02      75689
03      44398
11      37150
12      22997
00      12965
21       8807
22       3992
32       1541
31        819
41        758
42        307
51        167
52         17
53          5
Name: count, dtype: int64

In [77]:
df["caractereEmployeurEtablissement"].value_counts()

caractereEmployeurEtablissement
N    1375286
O     550220
Name: count, dtype: int64

In [78]:
df["categorieJuridiqueUniteLegale"].value_counts()

categorieJuridiqueUniteLegale
5710    669560
5499    383719
6540    329650
9220    222391
9110     69068
         ...
5658         1
6554         1
6100         1
5670         1
5203         1
Name: count, Length: 219, dtype: int64

In [87]:
df_temp = df[
    (df["denominationUsuelleEtablissement"].isna()) &
    (df["denominationUniteLegale"].isna())
]

In [93]:
df["non_entreprise"] = np.where(
    df["denominationUsuelleEtablissement"].isna(),
    df["denominationUniteLegale"],
    df["denominationUsuelleEtablissement"]
)

In [98]:
df.info()

<class 'pandas.DataFrame'>
Index: 1935366 entries, 0 to 2966639
Data columns (total 25 columns):
 #   Column                                  Dtype
---  ------                                  -----
 0   siren                                   str
 1   siret                                   str
 2   dateCreationEtablissement               object
 3   trancheEffectifsEtablissement           str
 4   denominationUsuelleEtablissement        str
 5   dateDernierTraitementEtablissement      datetime64[us]
 6   etablissementSiege                      bool
 7   numeroVoieEtablissement                 str
 8   typeVoieEtablissement                   str
 9   libelleVoieEtablissement                str
 10  codePostalEtablissement                 str
 11  libelleCommuneEtablissement             str
 12  coordonneeLambertAbscisseEtablissement  str
 13  coordonneeLambertOrdonneeEtablissement  str
 14  etatAdministratifEtablissement          str
 15  activitePrincipaleEtablissement         str
 16  caractereEmployeurEtablissement         str
 17  codePaysEtrangerEtablissement           str
 18  denominationUniteLegale                 str
 19  sexeUniteLegale                         str
 20  prenomUsuelUniteLegale                  str
 21  trancheEffectifsUniteLegale             str
 22  categorieEntreprise                     str
 23  categorieJuridiqueUniteLegale           int64
 24  non_entreprise                          str
dtypes: bool(1), datetime64[us](1), int64(1), object(1), str(21)
memory usage: 620.5+ MB

In [99]:
df_temp = df[
    (df["coordonneeLambertAbscisseEtablissement"].isna())
]

In [103]:
df_temp["activitePrincipaleEtablissement"].value_counts()

activitePrincipaleEtablissement
68.20B    15838
94.99Z     5835
68.20A     3067
70.22Z     2592
93.12Z     2025
          ...
01.15Z        1
26.52Z        1
65.20Z        1
17.24Z        1
28.99A        1
Name: count, Length: 639, dtype: int64

In [104]:
print(df_temp["activitePrincipaleEtablissement"].value_counts().to_string())

activitePrincipaleEtablissement
68.20B    15838
94.99Z     5835
68.20A     3067
70.22Z     2592
93.12Z     2025
81.10Z     1864
70.10Z     1737
64.20Z     1316
47.71Z     1315
56.10C     1272
56.10A     1102
90.01Z     1094
62.02A      998
88.99B      987
49.32Z      833
01.11Z      805
66.30Z      770
43.99C      733
71.12B      662
45.11Z      612
41.20A      590
45.20A      590
68.31Z      561
41.10D      560
43.21A      518
68.32A      515
85.59A      474
49.41B      464
62.01Z      450
96.02A      428
47.78C      423
82.99Z      413
43.34Z      412
93.29Z      398
68.10Z      377
43.22A      374
47.91B      373
46.90Z      362
55.10Z      335
47.11B      319
84.11Z      319
35.11Z      317
85.20Z      313
85.59B      312
81.21Z      307
64.19Z      304
88.91A      302
47.78A      289
86.21Z      271
56.29B      269
69.20Z      264
43.32A      263
47.72A      263
64.30Z      262
49.41A      256
96.09Z      252
82.11Z      251
96.02B      248
10.71C      247
81.30Z      244
43.22B      233
47.75Z      228
73.11Z      225
47.73Z      218
82.30Z      215
90.02Z      213
41.20B      213
66.19A      213
69.10Z      211
66.22Z      210
55.20Z      209
70.21Z      207
47.91A      205
94.20Z      205
94.91Z      203
74.90B      201
85.51Z      201
46.69B      198
85.10Z      198
74.10Z      196
80.10Z      196
71.11Z      193
93.19Z      191
59.20Z      189
46.49Z      187
77.11A      184
86.22C      181
47.77Z      181
52.29B      179
47.62Z      179
47.11D      178
47.30Z      178
52.21Z      177
47.29Z      176
52.10B      174
47.59A      174
56.30Z      170
85.52Z      170
59.11A      162
46.73A      161
72.19Z      158
46.42Z      158
46.19B      158
86.23Z      157
47.76Z      157
43.32B      156
43.33Z      150
56.29A      148
47.81Z      146
42.99Z      146
93.11Z      142
47.22Z      141
47.59B      140
41.10A      139
56.21Z      138
88.10A      134
47.64Z      133
82.19Z      133
96.01B      133
59.11C      131
47.42Z      131
85.53Z      131
47.19B      128
66.19B      126
43.31Z      123
84.12Z      123
59.11B      122
01.61Z      122
71.20B      119
68.32B      119
78.30Z      119
43.12A      118
58.29C      112
81.22Z      112
36.00Z      112
47.24Z      111
43.91B      111
85.31Z      109
46.39B      108
46.51Z      105
78.20Z      103
37.00Z      101
47.74Z       99
43.29A       97
46.52Z       96
58.14Z       95
79.11Z       94
52.23Z       93
14.13Z       91
86.10Z       86
02.40Z       85
61.10Z       85
84.13Z       85
45.32Z       84
43.39Z       83
85.42Z       83
46.69C       77
47.51Z       75
63.11Z       74
46.46Z       73
77.32Z       73
46.45Z       72
96.03Z       71
35.13Z       70
74.20Z       69
71.20A       69
94.12Z       69
46.21Z       69
47.21Z       69
43.99B       69
01.43Z       68
96.04Z       68
61.90Z       68
43.99A       68
80.20Z       67
95.29Z       66
51.10Z       66
87.10A       66
38.21Z       66
65.12Z       66
77.35Z       66
47.54Z       65
90.04Z       64
77.29Z       63
46.31Z       62
47.72B       62
08.12Z       62
47.65Z       61
45.31Z       61
43.29B       61
87.30A       60
93.13Z       59
86.90B       59
47.25Z       59
46.18Z       58
47.41Z       57
77.39Z       57
01.50Z       56
72.11Z       56
94.11Z       56
47.11C       56
91.03Z       55
86.90A       55
49.31Z       55
43.99D       53
55.90Z       53
33.12Z       53
74.90A       52
86.90F       52
25.62B       51
45.40Z       51
46.34Z       51
90.03B       51
53.10Z       51
46.69A       50
47.79Z       50
87.90A       50
47.61Z       49
73.12Z       49
58.11Z       48
38.32Z       48
01.62Z       48
86.90E       47
38.11Z       47
35.30Z       47
87.90B       47
95.23Z       47
47.52A       46
90.03A       44
18.13Z       44
02.20Z       44
85.32Z       43
18.12Z       43
49.39B       43
63.12Z       42
41.10C       42
59.12Z       41
86.90D       41
47.89Z       41
47.99B       40
93.21Z       40
84.24Z       40
79.90Z       40
47.52B       40
49.10Z       40
81.29A       39
55.30Z       39
01.13Z       39
35.14Z       39
31.09B       38
46.41Z       37
02.10Z       37
46.74A       37
42.11Z       37
75.00Z       37
88.10C       36
33.20A       36
47.11F       36
43.32C       35
46.38B       34
46.75Z       34
46.61Z       34
25.61Z       34
62.09Z       33
46.63Z       33
64.92Z       33
87.20A       33
86.22B       33
78.10Z       32
49.42Z       32
32.50A       32
59.14Z       32
46.76Z       32
46.47Z       32
35.21Z       32
46.14Z       31
01.49Z       31
72.20Z       31
46.71Z       31
47.11A       31
53.20Z       30
10.71D       30
87.10B       30
46.73B       30
47.26Z       30
46.72Z       29
94.92Z       29
49.39A       29
95.11Z       29
86.22A       28
46.74B       27
64.99Z       27
77.21Z       27
77.40Z       27
85.60Z       27
23.63Z       27
60.10Z       27
88.99A       26
45.19Z       26
45.20B       26
25.11Z       26
73.20Z       26
52.29A       25
91.01Z       25
42.21Z       25
77.12Z       24
74.30Z       24
46.43Z       24
61.20Z       24
39.00Z       23
77.31Z       23
95.12Z       23
01.47Z       22
84.23Z       22
33.16Z       22
58.19Z       22
77.11B       21
87.10C       21
46.66Z       21
33.20D       20
79.12Z       20
26.51B       20
47.99A       20
62.03Z       19
33.20B       19
43.91A       19
47.82Z       18
66.12Z       18
46.44Z       18
32.99Z       18
10.82Z       18
47.53Z       18
42.22Z       18
20.42Z       18
58.29A       17
66.21Z       17
10.89Z       17
58.13Z       17
43.11Z       17
46.23Z       17
35.23Z       17
46.13Z       16
52.24B       16
46.19A       16
84.25Z       16
91.02Z       16
88.91B       16
01.24Z       16
29.20Z       16
43.99E       16
46.17B       16
62.02B       16
01.21Z       15
91.04Z       15
33.20C       15
23.70Z       15
25.99B       15
32.12Z       15
95.22Z       15
10.71B       15
10.71A       15
84.30B       14
84.30A       14
63.91Z       14
10.13B       14
46.22Z       14
01.30Z       14
30.30Z       14
81.29B       14
52.10A       13
99.00Z       13
64.91Z       13
25.12Z       13
47.23Z       13
26.30Z       13
71.12A       12
50.40Z       12
27.90Z       12
82.20Z       12
22.29A       12
49.50Z       12
41.10B       12
46.62Z       11
46.33Z       11
88.10B       11
01.41Z       11
23.99Z       11
15.12Z       11
46.11Z       11
47.43Z       11
28.99B       11
63.99Z       11
33.14Z       10
23.61Z       10
25.50B       10
17.29Z       10
46.36Z       10
56.10B       10
28.25Z       10
29.32Z       10
43.12B       10
46.38A       10
46.32A       10
21.20Z       10
10.83Z       10
60.20B       10
58.21Z        9
96.01A        9
20.11Z        9
01.19Z        9
46.65Z        9
10.72Z        9
95.21Z        9
14.19Z        9
10.11Z        9
50.30Z        9
86.90C        8
26.12Z        8
16.23Z        8
46.12B        8
82.92Z        8
95.25Z        8
23.19Z        8
95.24Z        8
46.16Z        8
33.13Z        8
23.12Z        8
59.13B        8
35.12Z        8
59.13A        7
87.20B        7
08.11Z        7
26.11Z        7
65.11Z        7
18.14Z        7
10.13A        7
13.92Z        7
16.29Z        7
49.20Z        7
33.11Z        7
01.70Z        7
26.40Z        6
32.13Z        6
43.13Z        6
20.41Z        6
11.01Z        6
38.12Z        6
42.91Z        6
49.41C        6
22.23Z        6
22.22Z        6
28.41Z        6
25.73B        6
87.30B        6
26.70Z        6
10.51C        6
16.24Z        6
46.39A        6
24.20Z        6
10.85Z        6
47.78B        6
31.01Z        6
46.17A        6
28.22Z        6
82.91Z        6
35.22Z        6
32.20Z        6
11.05Z        6
01.45Z        6
10.52Z        6
01.29Z        6
28.29B        5
20.30Z        5
22.29B        5
10.61A        5
51.21Z        5
46.37Z        5
20.14Z        5
27.12Z        5
13.99Z        5
47.63Z        5
77.33Z        5
24.10Z        5
25.50A        5
28.93Z        4
32.40Z        4
28.12Z        4
38.22Z        4
52.22Z        4
32.50B        4
28.13Z        4
47.19A        4
10.51A        4
25.62A        4
01.42Z        4
03.22Z        4
92.00Z        4
10.39A        4
42.12Z        4
58.29B        4
33.17Z        4
46.77Z        4
16.10A        4
28.30Z        4
29.10Z        4
20.20Z        4
46.15Z        4
46.64Z        3
22.19Z        3
24.54Z        3
13.96Z        3
46.32C        3
27.40Z        3
20.59Z        3
46.48Z        3
46.32B        3
25.73A        3
26.20Z        3
23.13Z        3
31.09A        3
20.15Z        3
14.39Z        3
58.12Z        3
66.11Z        3
20.16Z        3
18.20Z        3
10.20Z        3
23.41Z        3
66.29Z        3
16.10B        3
77.34Z        3
19.20Z        3
50.10Z        3
27.11Z        3
10.41A        3
11.07B        3
10.32Z        2
16.21Z        2
28.91Z        2
09.10Z        2
27.32Z        2
23.62Z        2
26.51A        2
20.51Z        2
10.73Z        2
60.20A        2
15.20Z        2
24.53Z        2
33.15Z        2
25.40Z        2
84.30C        2
25.99A        2
46.24Z        2
61.30Z        2
65.30Z        2
28.14Z        2
06.10Z        2
17.21B        2
17.12Z        2
10.91Z        2
38.31Z        2
31.02Z        2
24.33Z        2
24.42Z        2
77.22Z        2
10.31Z        2
50.20Z        2
13.30Z        2
27.33Z        2
28.49Z        2
21.10Z        2
20.53Z        2
10.39B        2
25.72Z        2
01.25Z        2
80.30Z        2
43.21B        2
01.16Z        1
03.11Z        1
84.21Z        1
23.51Z        1
32.91Z        1
28.11Z        1
46.12A        1
14.20Z        1
10.84Z        1
20.13A        1
17.21A        1
14.11Z        1
27.51Z        1
23.32Z        1
28.21Z        1
17.22Z        1
28.92Z        1
28.15Z        1
30.11Z        1
08.92Z        1
14.14Z        1
42.13A        1
24.51Z        1
23.91Z        1
09.90Z        1
01.28Z        1
15.11Z        1
30.20Z        1
23.49Z        1
01.26Z        1
33.19Z        1
25.71Z        1
30.12Z        1
23.69Z        1
16.22Z        1
31.03Z        1
47.11E        1
25.21Z        1
17.23Z        1
28.29A        1
10.92Z        1
25.92Z        1
25.29Z        1
10.51D        1
32.30Z        1
24.45Z        1
11.07A        1
26.60Z        1
27.31Z        1
25.30Z        1
03.21Z        1
30.92Z        1
26.80Z        1
13.91Z        1
03.12Z        1
23.14Z        1
01.46Z        1
01.15Z        1
26.52Z        1
65.20Z        1
17.24Z        1
28.99A        1

In [107]:
df["niv1_activitePrincipaleEtablissement"] = df["activitePrincipaleEtablissement"].str[:2]

In [110]:
print(df["niv1_activitePrincipaleEtablissement"].value_counts().to_string())

niv1_activitePrincipaleEtablissement
68    471258
70    165087
94    121265
47    106703
43     91146
81     84546
56     69263
46     66750
62     58725
64     52305
66     47662
85     44543
49     43491
41     39380
90     38332
93     33076
96     30787
82     28330
71     27177
59     26736
45     26395
88     26017
77     23865
86     20060
69     19842
74     18718
55     16248
58     12811
73     10528
10      9406
35      7792
52      7260
80      7105
84      6485
63      6208
14      5546
01      4824
72      4518
78      4392
87      4263
79      3982
95      3825
32      3371
61      3126
33      2810
42      2180
18      2156
25      2060
53      1885
65      1873
38      1711
02      1478
20      1400
91      1359
26      1121
31      1052
28       896
23       874
37       827
75       708
27       668
60       633
13       604
99       573
36       525
15       512
22       480
16       449
51       428
11       415
29       393
50       384
17       269
39       267
30       259
08       216
24       210
21       206
92       115
06        87
09        43
03        36
19        28
07        17
12         6
97         2
00         1
05         1

In [111]:
df_temp = df[
    (df["coordonneeLambertAbscisseEtablissement"].isna())
]

In [112]:
print(df_temp["niv1_activitePrincipaleEtablissement"].value_counts().to_string())

niv1_activitePrincipaleEtablissement
68    20477
47     6848
94     6397
70     4536
43     3727
56     3109
93     2855
46     2736
81     2580
85     2061
64     1955
49     1777
41     1556
62     1516
88     1512
90     1466
45     1450
66     1360
01     1286
96     1209
71     1055
82     1038
86     1018
59      692
52      681
55      636
84      636
77      575
74      542
35      536
69      475
10      441
58      327
87      320
73      300
80      265
78      254
72      245
42      237
95      205
33      197
61      179
25      178
38      173
02      166
79      154
63      141
36      112
91      111
14      106
37      101
18       97
23       93
32       87
53       81
65       76
51       71
08       70
26       68
28       66
20       61
31       50
60       39
75       37
22       32
16       31
29       30
27       29
50       26
39       23
24       22
17       18
13       18
30       18
11       16
15       14
99       13
21       12
03        7
92        4
09        3
19        3
06        2